version: "3.5"
services:
  phonecatalog:
    image: lordkener/phonecatalog-app:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - phonecatalog-network
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - phonecatalog-mysql

  phonecatalog-mysql:
    image: mysql:5.7
    restart: on-failure
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - phonecatalog-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=phonecatalog
      
networks:
  phonecatalog-network: 